apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nishank841/kube-helm.git
    targetRevision: main
    path: manifests/services

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
